import Nav from '@/components/nav'
import './globals.css'
import { Poppins } from 'next/font/google'
const poppins = Poppins({ weight: ["500", "600", "700", "800", "900"], subsets: ["latin"] })

export const metadata = {
  title: 'Portofolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={poppins.className}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
